# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, CI ]
  pull_request:
    branches: [ master, CI ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: [5432:5432]
        env:
          POSTGRES_USER: ci
          POSTGRES_DB: crs_hays_test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
      - name: Install bundler gem
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
